language: php

php:
        - 5.4
        - 5.5
        - 5.6
        - 7.0

before_script:
        - echo 'upload_tmp_dir = "/tmp"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit --configuration tests/phpunit.cerb.platform.xml
